- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - "{{ myvarfile }}"
  tasks:
    - name: Migrating Vm from source to destination
      command: pwsh ./script/migration.ps1
      ignore_errors: yes
      changed_when: false
      register: powershell_output
    - name: Display migration output
      debug:
        msg: {{ powershell_output }}
